recipe_root: /Users/priyatam/Dev/github/facjure/poetroid/client
content: /Users/priyatam/Dev/github/facjure/poetroid-poems/poems
routes:
    - js/controller.js

first_page: blog
default_template: poem.mustache

title: Discover Poetry Together
version: 0.4
build: 279
