content: /Users/priyatam/Dev/github/facjure/poems
recipe_root: /Users/priyatam/Dev/github/facjure/poetics
lib: /Users/priyatam/Dev/github/facjure/poetics/lib

first_page: blog
default_template: post_plain.mustache

title: Discover Poetry Together

