content: /Users/priyatam/Dev/github/facjure/poems
recipe_root: /Users/priyatam/Dev/github/facjure/poetics

first_page: blog
default_template: post_plain.mustache

title: Discover Poetry, Read Anywhere, Curate Poems Together

