recipe_root: /Users/priyatam/Dev/github/facjure/poetics
content: /Users/priyatam/Dev/github/facjure/poems
routes:
    - js/controller.js

first_page: blog
default_template: poem.mustache

title: Discover Poetry Together

